[package]
name = "sondehub-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.41.1", features = ["full"] }
reqwest = { version = "0.12.9", features = ["gzip", "json"] }
serde_json = "1.0.133"
serde = { version = "1.0.216", features = ["derive"] }